// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDU3zQJCkKQ6lVe43dorR-y804wVJr2w',
    appId: '1:59642762439:web:66118bb81ee6a23d921ae2',
    messagingSenderId: '59642762439',
    projectId: 'flutter-vehiculos-34686',
    authDomain: 'flutter-vehiculos-34686.firebaseapp.com',
    storageBucket: 'flutter-vehiculos-34686.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0--DR_RhnuE2ckZ5mmw4-VK6_7GCLKJE',
    appId: '1:59642762439:android:b728e2f2cfefc3d8921ae2',
    messagingSenderId: '59642762439',
    projectId: 'flutter-vehiculos-34686',
    storageBucket: 'flutter-vehiculos-34686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBubwW5uN0kAZvwE3COWZSd4WoPinxbf5o',
    appId: '1:59642762439:ios:7b5c6fbd19fc2092921ae2',
    messagingSenderId: '59642762439',
    projectId: 'flutter-vehiculos-34686',
    storageBucket: 'flutter-vehiculos-34686.appspot.com',
    iosClientId: '59642762439-3ju7rlmdf7h8pa6g8kb4iddmodqkv7rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.p4Vh2549162018',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBubwW5uN0kAZvwE3COWZSd4WoPinxbf5o',
    appId: '1:59642762439:ios:7b5c6fbd19fc2092921ae2',
    messagingSenderId: '59642762439',
    projectId: 'flutter-vehiculos-34686',
    storageBucket: 'flutter-vehiculos-34686.appspot.com',
    iosClientId: '59642762439-3ju7rlmdf7h8pa6g8kb4iddmodqkv7rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.p4Vh2549162018',
  );
}
